### ISSUE TITLE
Adding Edited Items Currency

### ISSUE THREAD

**Issue by TraipsingShadow** [nikosgram13/Gringotts#111]
Minecraft Version: 1.18.2/Paper
Gringotts Version: gringotts-2.12.4-SNAPSHOT.jar
With Vault? Yes

**Is your feature request related to a problem? Please describe.**
As of the moment, there seems to be no clear way of creating a "custom" item currency. Say I want to create a currency that uses the "paper" Minecraft item. The current config provides a way to add a custom name (unclear if color codes or hex codes work as the docs don't seem to provide an example) and lore.

But what if I wanted a custom Paper that has an Unbreaking X enchant that has a hidden flag with a custom name and lore?

**Describe the solution you'd like**
An ability to have more flexibility when creating items for currency

**Describe alternatives you've considered**
None

**Additional context**
A side note, but any edits I made to the config makes the console unhappy:

![image](https://user-images.githubusercontent.com/70948121/190196065-33bb7bff-af1a-4dc4-ae7e-1c8a3e8a290e.png)

**Comment by nikosgram** [comment]
Gringotts v2.12.4-SNAPSHOT is currently only supporting Spigot/Paper 1.19+

Though, I'll spend some time investigating the issue :) I might have an idea why is that.

**Comment by TraipsingShadow** [comment]
Ah, that's why! Noted. What is the last version to support 1.18.2?

**Comment by nikosgram** [comment]
Hello @CastedShadow, I tried to reproduce the issue on paper 1.18.2 but I couldn't. Are you sue the configuration file is been written properly?

![image](https://user-images.githubusercontent.com/3318873/190213545-065ad069-db05-4d84-bd09-8b60a75838b2.png)

I highly recommend using a yaml lint tool to verify that they are not weird spaces in the config file :)

http://www.yamllint.com/

**Comment by nikosgram** [comment]
Seems like it's working correctly on version 1.18.2 of papermc :)

**Comment by TraipsingShadow** [comment]
Hi! I restarted the server with this:
![image](https://user-images.githubusercontent.com/70948121/190215162-3ccce09f-86fa-49cf-894f-82e6b2596679.png)
and when I check the balance or money type, the entire config file is disregarded. It might be an issue on my end using 1.18.2?

**Comment by nikosgram** [comment]
Hello @CastedShadow, I can see the issue you having. Yaml syntax is really vulnerable to wrong spaces. 

Try this instead:

```yaml
# for details on configuration, see https://github.com/MinecraftWars/Gringotts/blob/master/doc/configuration.md

# supported languages: "custom" (default, english) and "de" (german)
language: custom

# regex that create a vault if matches with a sign
vault_pattern: '[^\[]*\[(\w*) ?vault\]'

# currency name and value config
currency:
  # currency name to use in messages
  name:
    singular: Ticket
    plural: Tickets

  # number of decimal digits supported by currency value (0 for whole numbers only)
  digits: 0

  # Display account balances with individual denomination names
  named-denominations: false

  # value of individual denominations. default: emerald: 1, emerald block: 9
  denominations:
    - material: paper
      value: 1
#      unit-name: Emeralde
#      unit-name-plural: Emeraldes
      displayname: '&eTicket'
#      damage: 10
#      custom_model_data: 1
#      lore:
#        - line1
#        - line2

# tax on /money pay transactions
transactiontax:
  flat: 0.0
  rate: 0.0

# balance to start an account with (purely virtual)
startingbalance:
  player: 0
  faction: 0
  town: 0
  nation: 0

# globally (dis)allow use of vault types
usevault:
  container: true
  enderchest: true

# whether money/balance commands show vault and inventory balance separately
balance:
  show-vault: true
  show-inventory: true

```
